# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_auto_20160306_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
