# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_loan_monthly_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
