# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0004_auto_20160309_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loans',
        ),
        migrations.AddField(
            model_name='expense',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.Profile'),
        ),
        migrations.AddField(
            model_name='loan',
            name='people',
            field=models.ManyToManyField(to='loanapp.Profile'),
        ),
    ]
