# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0007_auto_20160311_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='account',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='User1', max_length=100),
        ),
    ]
