# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0009_auto_20160311_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='User1', max_length=100),
        ),
    ]
