# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0011_auto_20160316_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remaining_amt', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('interest', models.DecimalField(decimal_places=5, max_digits=10)),
                ('monthly_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='person',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_payment',
            new_name='min_monthly_amt',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='principal',
            new_name='original_amt',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='account',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='people',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_amt',
            field=models.DecimalField(decimal_places=2, default='10.0', max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_amt',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.Loan'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.Loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='person',
            field=models.ManyToManyField(to='loanapp.Person'),
        ),
    ]
