# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0013_auto_20160321_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='acct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.Account'),
        ),
    ]
