# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-25 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0014_loan_acct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='person',
        ),
        migrations.AddField(
            model_name='loan',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanapp.Person'),
        ),
    ]
