# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0016_auto_20160425_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='down_amt',
            field=models.DecimalField(decimal_places=2, default=b'0', max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=5, default=b'2.0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='min_monthly_amt',
            field=models.DecimalField(decimal_places=2, default=b'0.0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_amt',
            field=models.DecimalField(decimal_places=2, default=b'0.0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='original_amt',
            field=models.DecimalField(decimal_places=2, default=b'100.0', max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_amt',
            field=models.DecimalField(decimal_places=2, default=b'100.0', max_digits=100, null=True),
        ),
    ]
