# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0018_profile_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='plan_amount',
            field=models.DecimalField(decimal_places=2, default=b'0.0', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='plan_category',
            field=models.CharField(default=b'0.0', max_length=100),
        ),
    ]
