# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0019_auto_20161202_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='plan_amount',
            field=models.DecimalField(decimal_places=2, default=b'0.0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='plan_category',
            field=models.CharField(default=b'0.0', max_length=100, null=True),
        ),
    ]
